package com.dahua.bean

import com.dahua.tools.NumberFormat

/**
 * 日志实体类
 */

class LogBean(val sessionid: String, /* 会话ID */
              val advertisersid: Int,
              val adorderid: Int,
              val adcreativeid: Int,
              val adplatformproviderid: Int,
              val sdkversion: String,
              val adplatformkey: String,
              val putinmodeltype: Int,
              val requestmode: Int,
              val adprice: Double,
              val adppprice: Double,
              val requestdate: String,
              val ip: String,
              val appid: String,
              var appname: String,
              val uuid: String,
              val device: String,
              val client: Int,
              val osversion: String,
              val density: String,
              val pw: Int,
              val ph: Int,
              val longitude: String,
              val lat: String,
              val provincename: String,
              val cityname: String,
              val ispid: Int,
              val ispname: String,
              val networkmannerid: Int,
              val networkmannername: String,
              val iseffective: Int,
              val isbilling: Int,
              val adspacetype: Int,
              val adspacetypename: String,
              val devicetype: Int,
              val processnode: Int,
              val apptype: Int,
              val district: String,
              val paymode: Int,
              val isbid: Int,
              val bidprice: Double,
              val winprice: Double,
              val iswin: Int,
              val cur: String,
              val rate: Double,
              val cnywinprice: Double,
              val imei: String,
              val mac: String,
              val idfa: String,
              val openudid: String,
              val androidid: String,
              val rtbprovince: String,
              val rtbcity: String,
              val rtbdistrict: String,
              val rtbstreet: String,
              val storeurl: String,
              val realip: String,
              val isqualityapp: Int,
              val bidfloor: Double,
              val aw: Int,
              val ah: Int,
              val imeimd5: String,
              val macmd5: String,
              val idfamd5: String,
              val openudidmd5: String,
              val androididmd5: String,
              val imeisha1: String,
              val macsha1: String,
              val idfasha1: String,
              val openudidsha1: String,
              val androididsha1: String,
              val uuidunknow: String,
              val userid: String,
              val iptype: Int,
              val initbidprice: Double,
              val adpayment: Double,
              val agentrate: Double,
              val lomarkrate: Double,
              val adxrate: Double,
              val title: String,
              val keywords: String,
              val tagid: String,
              val callbackdate: String,
              val channelid: String,
              val mediatype: Int
             ) {

}

object LogBean {
  /**
   * 传入一个字符串数组来构建一个logbean
   *
   * @param line
   * @return
   */
  def apply(line: Array[String]): LogBean = new LogBean(
    line(0),
    NumberFormat.toInt(line(1)),
    NumberFormat.toInt(line(2)),
    NumberFormat.toInt(line(3)),
    NumberFormat.toInt(line(4)),
    line(5),
    line(6),
    NumberFormat.toInt(line(7)),
    NumberFormat.toInt(line(8)),
    NumberFormat.toDouble(line(9)),
    NumberFormat.toDouble(line(10)),
    line(11),
    line(12),
    line(13),
    line(14),
    line(15),
    line(16),
    NumberFormat.toInt(line(17)),
    line(18),
    line(19),
    NumberFormat.toInt(line(20)),
    NumberFormat.toInt(line(21)),
    line(22),
    line(23),
    line(24),
    line(25),
    NumberFormat.toInt(line(26)),
    line(27),
    NumberFormat.toInt(line(28)),
    line(29),
    NumberFormat.toInt(line(30)),
    NumberFormat.toInt(line(31)),
    NumberFormat.toInt(line(32)),
    line(33),
    NumberFormat.toInt(line(34)),
    NumberFormat.toInt(line(35)),
    NumberFormat.toInt(line(36)),
    line(37),
    NumberFormat.toInt(line(38)),
    NumberFormat.toInt(line(39)),
    NumberFormat.toDouble(line(40)),
    NumberFormat.toDouble(line(41)),
    NumberFormat.toInt(line(42)),
    line(43),
    NumberFormat.toDouble(line(44)),
    NumberFormat.toDouble(line(45)),
    line(46),
    line(47),
    line(48),
    line(49),
    line(50),
    line(51),
    line(52),
    line(53),
    line(54),
    line(55),
    line(56),
    NumberFormat.toInt(line(57)),
    NumberFormat.toDouble(line(58)),
    NumberFormat.toInt(line(59)),
    NumberFormat.toInt(line(60)),
    line(61),
    line(62),
    line(63),
    line(64),
    line(65),
    line(66),
    line(67),
    line(68),
    line(69),
    line(70),
    line(71),
    line(72),
    NumberFormat.toInt(line(73)),
    NumberFormat.toDouble(line(74)),
    NumberFormat.toDouble(line(75)),
    NumberFormat.toDouble(line(76)),
    NumberFormat.toDouble(line(77)),
    NumberFormat.toDouble(line(78)),
    line(79),
    line(80),
    line(81),
    line(82),
    line(83),
    NumberFormat.toInt(line(84)
    ))

}
